### ISSUE TITLE
Someone taking credit for your work

### ISSUE THREAD

**Issue by kescobo** [iliaschalkidis/LegalCrawler#3]
Hi there - just wanted to alert you to someone (possibly a bot) is trying to pass your work off as their own. 

https://github.com/Salvelop07/Legal-Crawler

They appear to have done this to a lot of repos - I was only able to find yours because they didn't realize that your Citation section has your name encoded in it.

![image](https://github.com/user-attachments/assets/afff7fe4-a061-4eea-bcf6-349b921adcdf)

**Comment by kescobo** [comment]
They're not really even trying to hide it https://github.com/Salvelop07/Legal-Crawler/commit/55b8ae125d3b29ed658683c8e1e311f6db547be0#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15R79-L88

**Comment by iliaschalkidis** [comment]
Best of luck! What can I say? 😄 Fake it till you make it....

**Comment by kescobo** [comment]
It's a great attitude - you're more magnanimous than I would be! Keep up the good work :+1:
